#!/usr/bin/env python3
"""Convert IEEE oui.csv to a sorted C header for ESP32 flash lookup."""
import argparse
import csv
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="IEEE oui.csv")
    parser.add_argument("--output", required=True, help="C header path")
    parser.add_argument("--max", type=int, default=5500)
    args = parser.parse_args()

    rows = []
    with open(args.input, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            assignment = row["Assignment"].strip().upper()
            org = row["Organization Name"].strip().replace('"', "'")
            if len(assignment) != 6 or not assignment.isalnum():
                continue
            rows.append((assignment, org[:31]))

    rows = sorted(set(rows))[: args.max]

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/generate-oui-db.py - do not edit by hand\n")
        f.write("#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\n\n")
        f.write(f"static const uint16_t OUI_COUNT = {len(rows)};\n")
        f.write("struct OuiEntry { uint8_t prefix[3]; const char* vendor; };\n")
        f.write("static const OuiEntry OUI_TABLE[] PROGMEM = {\n")
        for prefix, org in rows:
            b = (int(prefix[0:2], 16), int(prefix[2:4], 16), int(prefix[4:6], 16))
            f.write(f'    {{ {{0x{b[0]:02X}, 0x{b[1]:02X}, 0x{b[2]:02X}}}, "{org}" }},\n')
        f.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
